// AM Games — single-player mini games
const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
let ttt=['','','','','','','','',''],tttOver=false,thinking=false;
function winner(b){for(const w of wins)if(b[w[0]]&&b[w[0]]===b[w[1]]&&b[w[1]]===b[w[2]])return b[w[0]];return b.every(Boolean)?'D':''}
function drawTic(){const el=document.getElementById('board');el.innerHTML='';ttt.forEach((v,i)=>{const c=document.createElement('button');c.className='ttt-cell';c.textContent=v;c.onclick=()=>ticMove(i);c.disabled=!!v||tttOver||thinking;el.appendChild(c)});document.getElementById('ttt-status').textContent=tttOver?'Game over. Press Reset to play again.':thinking?'AM is thinking…':'Your turn — X';}
function minimax(b,isMax){const r=winner(b);if(r==='O')return 10;if(r==='X')return -10;if(r==='D')return 0;let best=isMax?-Infinity:Infinity;for(let i=0;i<9;i++)if(!b[i]){b[i]=isMax?'O':'X';const v=minimax(b,!isMax);b[i]='';best=isMax?Math.max(best,v):Math.min(best,v)}return best}
function aiMove(){let best=-Infinity,move=-1;for(let i=0;i<9;i++)if(!ttt[i]){ttt[i]='O';const v=minimax(ttt,false);ttt[i]='';if(v>best){best=v;move=i}}if(move>=0)ttt[move]='O';const r=winner(ttt);if(r){tttOver=true}else thinking=false;drawTic()}
function ticMove(i){if(ttt[i]||tttOver||thinking)return;ttt[i]='X';let r=winner(ttt);if(r){tttOver=true;drawTic();return}thinking=true;drawTic();setTimeout(aiMove,280)}
function resetTic(){ttt=['','','','','','','','',''];tttOver=false;thinking=false;drawTic()}resetTic();

const symbols=['◆','●','▲','■','★','✦'];let mem=[],open=[],matchedIndices=[],matched=0,lock=false;
function resetMemory(){mem=[...symbols,...symbols].sort(()=>Math.random()-.5);open=[];matchedIndices=[];matched=0;lock=false;drawMemory();document.getElementById('memory-status').textContent='Find all 6 pairs.'}
function drawMemory(){const el=document.getElementById('memory');el.innerHTML='';mem.forEach((s,i)=>{const c=document.createElement('button');c.className='memory-card '+(open.includes(i)?'flipped ':'')+(matchedIndices.includes(i)?'matched':'');c.textContent=s;c.onclick=()=>flipCard(i);el.appendChild(c)})}
function flipCard(i){if(lock||open.includes(i)||matchedIndices.includes(i))return;open.push(i);drawMemory();if(open.length===2){lock=true;if(mem[open[0]]===mem[open[1]]){matchedIndices.push(...open);matched++;open=[];lock=false;drawMemory();if(matched===6)document.getElementById('memory-status').textContent='Perfect match — you found them all!'}else setTimeout(()=>{open=[];lock=false;drawMemory()},650)}}resetMemory();

let secret=0,tries=0;function resetGuess(){secret=Math.floor(Math.random()*50)+1;tries=0;document.getElementById('guess-input').value='';document.getElementById('guess-status').textContent='You have unlimited tries.'}function makeGuess(){const n=Number(document.getElementById('guess-input').value),s=document.getElementById('guess-status');if(n<1||n>50){s.textContent='Enter a number from 1 to 50.';return}tries++;if(n===secret)s.textContent=`Correct! You got it in ${tries} ${tries===1?'try':'tries'}.`;else s.textContent=n<secret?'Too low — try again.':'Too high — try again.'}resetGuess();

// Reaction Test
let reactionTimer=null,reactionStart=0,reactionState='idle';function reactionDraw(){const b=document.getElementById('reaction-btn');if(!b)return;b.textContent=reactionState==='idle'?'Start':reactionState==='wait'?'Wait for it…':reactionState==='go'?'CLICK!':reactionState==='tooSoon'?'Too soon — try again':'Again';b.dataset.state=reactionState}function reactionStartGame(){clearTimeout(reactionTimer);reactionState='wait';reactionDraw();reactionTimer=setTimeout(()=>{reactionState='go';reactionStart=performance.now();reactionDraw()},900+Math.random()*2600)}function reactionClick(){if(reactionState==='idle'||reactionState==='tooSoon'||reactionState==='done'){reactionStartGame();return}if(reactionState==='wait'){clearTimeout(reactionTimer);reactionState='tooSoon';reactionDraw();return}const ms=Math.round(performance.now()-reactionStart);reactionState='done';reactionDraw();document.getElementById('reaction-status').textContent=`Your reaction time: ${ms} ms.`}reactionDraw();

// Dodge — tiny single-player survival game
let dodge={x:0,y:0,t:0,active:false,raf:0,last:0,obs:[]};function dodgeReset(){dodge={x:120,y:90,t:0,active:false,raf:0,last:0,obs:[]};const c=document.getElementById('dodge-canvas');if(c){c.width=600;c.height=300;drawDodge()}}function drawDodge(){const c=document.getElementById('dodge-canvas');if(!c)return;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--hover');x.fillRect(0,0,c.width,c.height);x.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--ink');x.fillRect(dodge.x,dodge.y,18,18);for(const o of dodge.obs){x.fillRect(o.x,o.y,18,18)}}function dodgeLoop(t){if(!dodge.active)return;const dt=Math.min(30,t-dodge.last);dodge.last=t;dodge.t+=dt;dodge.obs.forEach(o=>o.x-=.22*dt);if(Math.random()<dt/900)dodge.obs.push({x:600,y:20+Math.random()*260});dodge.obs=dodge.obs.filter(o=>o.x>-30);for(const o of dodge.obs)if(dodge.x<o.x+18&&dodge.x+18>o.x&&dodge.y<o.y+18&&dodge.y+18>o.y){dodge.active=false;document.getElementById('dodge-status').textContent=`You survived ${Math.floor(dodge.t/1000)}s.`;drawDodge();return}drawDodge();requestAnimationFrame(dodgeLoop)}function dodgeMove(dx,dy){if(!dodge.active)return;dodge.x=Math.max(0,Math.min(582,dodge.x+dx));dodge.y=Math.max(0,Math.min(282,dodge.y+dy));drawDodge()}function startDodge(){dodgeReset();dodge.active=true;dodge.last=performance.now();document.getElementById('dodge-status').textContent='Survive as long as you can. Use the buttons or arrow keys.';requestAnimationFrame(dodgeLoop)}document.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();dodgeMove(e.key==='ArrowLeft'?-12:e.key==='ArrowRight'?12:0,e.key==='ArrowUp'?-12:e.key==='ArrowDown'?12:0)}});dodgeReset();
